#!/usr/bin/python3
#
# Test that livepatch works

import os
import sys
import logging
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import QemuConfig, qemu_main, qemu_supports_p10, kvm_or_tcg
from utils import setup_logging, test_harness
from pexpect_utils import xmon_enter, xmon_exit


def test(name, cpu, machine):
    qconf = QemuConfig(machine)
    qconf.configure_from_env()
    qconf.cmdline = ''
    qconf.cloud_image = 'fedora34-cloudimg-ppc64le.qcow2'
    qconf.mem = '4G'
    qconf.cpu = cpu
    qconf.host_mounts = ['/home/michael/ci/build/output/selftests@ppc64le@ubuntu@20.04/install/livepatch/', '/home/michael/linux/lib/modules/']
    qconf.accel = kvm_or_tcg(machine, cpu)

    def test_livepatch(p):
        p.cmd('mkdir -p /lib/modules/$(uname -r)')
        p.cmd('mount -o bind /mnt/host1 /lib/modules/')
        p.cmd('ls -l /lib/modules/$(uname -r)/kernel/lib/livepatch/test_klp_livepatch.ko')
        p.send('cd /mnt/host0; ./test-livepatch.sh; cd -')
        for j in range(0, 3):
            i = p.expect(
                ['not ok',
                 'ok',
                 'ERROR: failed to complete transition',
                 "ERROR: could not insert 'test_klp_livepatch'",
                ], timeout=300)
            if i == 0:
                logging.error('Test failed')
            if i == 1:
                logging.info('Test PASSED')
            if i == 2:
                logging.error('Saw failure')
                return False
            if i == 3:
                logging.error('Test failed to run')
                return False

        return True


    qconf.callback = test_livepatch
    qconf.apply_defaults()

    return qemu_main(qconf)


def main():
    setup_logging()

    cpu = 'POWER9'
    machine = 'pseries'
    return test_harness(test, 'livepatch', cpu=cpu, machine=machine)


sys.exit(0 if main() else 1)
