name: Build & publish docker image
on:
  workflow_dispatch:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-deploy

    strategy:
      matrix:
        subarch: [ppc64le]
        image: [ ubuntu, ubuntu@22.04, ubuntu@21.10, ubuntu@21.04, ubuntu@20.04, ubuntu@18.04, ubuntu@16.04, fedora, fedora@36, fedora@35, fedora@34, fedora@33, korg@12.1.0, korg@11.3.0, korg@11.1.0, korg@10.3.0, korg@9.4.0, korg@9.3.0, korg@8.5.0, korg@8.1.0, korg@5.5.0 ]

    env:
      SUBARCH: ${{ matrix.subarch }}
      IMAGE: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: make -C build rebuild-image@$SUBARCH@$IMAGE

      - name: Push docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make -C build push-image@$SUBARCH@$IMAGE
